# Generated by Django 5.0.4 on 2024-04-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glowne_okno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polecenia',
            new_name='Polecenias',
        ),
    ]
