# Generated by Django 5.0.4 on 2024-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowne_okno', '0003_rename_polecenias_ksiazki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Book_Title', max_length=255)),
                ('author', models.CharField(db_column='Book_Author', max_length=255)),
                ('year_of_publication', models.CharField(db_column='Year_Of_Publication', max_length=4)),
                ('publisher', models.CharField(max_length=255)),
                ('image_url_s', models.URLField(db_column='Image_URL_S')),
                ('image_url_m', models.URLField(db_column='Image_URL_M')),
                ('image_url_l', models.URLField(db_column='Image_URL_L')),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_column='Book_Rating')),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ksiazki',
        ),
    ]
